import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

import { Share } from '@capacitor/share';
import { Geolocation } from '@capacitor/geolocation';
import { Camera, CameraResultType } from '@capacitor/camera';
import ResponsiveAppBar from '@/components/ResponsiveAppBar';
import CssBaseline from '@mui/material/CssBaseline';
import { styled } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import Paper from '@mui/material/Paper';

const inter = Inter({ subsets: ['latin'] });

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: 'center',
  color: theme.palette.text.secondary,
}));

export default function Home() {
  const share = async () => {
    await Share.share({
      title: 'SALON',
      text: 'SALON APP CURRENTLY BUILDING',
      url: '',
    });
  };

  const QCamera = async () => {
    // Take a picture or video, or load from the library
    const picture = await Camera.getPhoto({
      resultType: CameraResultType.Uri,
    });

    console.log('----00----');
    console.log(picture);
    console.log('====00====');
  };

  const getUserLocation = async () => {
    // get the users current position
    const position = await Geolocation.getCurrentPosition();

    // grab latitude & longitude
    const { latitude, longitude } = position.coords;

    console.log('----00----');
    console.log({ latitude, longitude });
    console.log('====00====');
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ResponsiveAppBar />

      <CssBaseline />

      <Grid container spacing={2}>
        <Grid item xs={6} md={8}>
          <Item>xs=6 md=8</Item>
        </Grid>
        <Grid item xs={6} md={4}>
          <Container maxWidth='sm'>
            <Button color='success' onClick={() => share()}>
              Share now!
            </Button>
            <Button color='success' onClick={() => getUserLocation()}>
              Get user location!
            </Button>
          </Container>
        </Grid>
        <Grid item xs={6} md={4}>
          <Item>xs=6 md=4</Item>
        </Grid>
        <Grid item xs={6} md={8}>
          <Item>xs=6 md=8</Item>
        </Grid>
      </Grid>
    </div>
  );
}
